package com.rupvm.covid19india.Constants;

public class ILiterals {
    public static final String BASE_URL = "https://api.covid19india.org/";
    public static final String STATE_WISE_URL = BASE_URL + "state_district_wise.json";
    public static final String STATE_DATA_COUNT_URL = BASE_URL +"data.json";
    public static final String LOG_URL =  BASE_URL +"updatelog/log.json"; ;



    public static final String[] STATE_ARRAY = {"Andaman and Nicobar Islands", "Andhra Pradesh", "Arunachal Pradesh",
            "Assam", "Bihar", "Chandigarh", "Chhattisgarh", "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh"
            , "Jammu and Kashmir", "Jharkhand", "Karnataka", "Kerala", "Ladakh", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya",
            "Mizoram", "Odisha", "Puducherry", "Punjab", "Rajasthan", "Tamil Nadu", "Telangana", "Tripura", "Uttar Pradesh", "Uttarakhand"
            , "West Bengal"};

    public static final String[][] DISTRICT_ARRAY= {{"North and Middle Andaman",
            "South Andaman",
            "Unknown"}, {"Anantapur",
            "Chittoor",
            "East Godavari",
            "Guntur",
            "Krishna",
            "Kurnool",
            "Prakasam",
            "S.P.S. Nellore",
            "Visakhapatnam",
            "West Godavari",
            "Y.S.R."}, {"Lohit"}, {
            "Cachar",
            "Dhubri",
            "Goalpara",
            "Golaghat",
            "Hailakandi",
            "Jorhat",
            "Kamrup",
            "Kamrup Metropolitan",
            "Lakhimpur",
            "Morigaon",
            "Nalbari",
            "South Salmara Mancachar",
            "Unknown"}, {"Aurangabad",
            "Banka",
            "Begusarai",
            "Bhagalpur",
            "Bhojpur",
            "Buxar",
            "East Champaran",
            "Gaya",
            "Gopalganj",
            "Kaimur Bhabua",
            "Lakhisarai",
            "Madhepura",
            "Munger",
            "Nalanda",
            "Nawada",
            "Patna",
            "Rohtas",
            "Saran",
            "Siwan",
            "Vaishali"}, {"Chandigarh"}, {"Bilaspur",
            "Durg",
            "Korba",
            "Raipur",
            "Rajnandgaon"}, {"Central Delhi",
            "East Delhi",
            "New Delhi",
            "North Delhi",
            "North East Delhi",
            "North West Delhi",
            "Shahdara",
            "South Delhi",
            "South East Delhi",
            "South West Delhi",
            "West Delhi",
            "Unknown"}, {"North Goa",
            "South Goa"}, {"Ahmadabad",
            "Anand",
            "Aravalli",
            "Banas Kantha",
            "Bharuch",
            "Bhavnagar",
            "Botad",
            "Chota Udaipur",
            "Dahod",
            "Gandhinagar",
            "Gir Somnath",
            "Jamnagar",
            "Kachchh",
            "Kheda",
            "Mahesana",
            "Mahisagar",
            "Morbi",
            "Narmada",
            "Navsari",
            "Panch Mahals",
            "Patan",
            "Porbandar",
            "Rajkot",
            "Sabar Kantha",
            "Surat",
            "Tapi",
            "Dang",
            "Vadodara",
            "Valsad"}, {"Ambala",
            "Bhiwani",
            "Charki Dadri",
            "Faridabad",
            "Fatehabad",
            "Gurugram",
            "Hisar",
            "Jind",
            "Kaithal",
            "Karnal",
            "Kurukshetra",
            "Nuh",
            "Palwal",
            "Panchkula",
            "Panipat",
            "Rohtak",
            "Sirsa",
            "Sonipat",
            "Yamunanagar",
            "Italians"}, {"Chamba",
            "Hamirpur",
            "Kangra",
            "Sirmaur",
            "Solan",
            "Una",
            "Unknown"}, {"Anantnag",
            "Badgam",
            "Bandipore",
            "Baramula",
            "Ganderbal",
            "Jammu",
            "Kathua",
            "Kishtwar",
            "Kulgam",
            "Kupwara",
            "Pulwama",
            "Rajouri",
            "Ramban",
            "Samba",
            "Shupiyan",
            "Srinagar",
            "Udhampur"}, {"Bokaro",
            "Deoghar",
            "Dhanbad",
            "Giridih",
            "Hazaribagh",
            "Kodarma",
            "Ranchi",
            "Simdega",
            "Unknown"}, {"Bagalkote",
            "Ballari",
            "Belagavi",
            "Bengaluru",
            "Bengaluru Rural",
            "Bidar",
            "Chikkaballapura",
            "Chitradurga",
            "Dakshina Kannada",
            "Davanagere",
            "Dharwad",
            "Gadag",
            "Kalaburagi",
            "Kodagu",
            "Mandya",
            "Mysuru",
            "Tumakuru",
            "Udupi",
            "Uttara Kannada",
            "Vijayapura"}, {"Alappuzha",
            "Ernakulam",
            "Idukki",
            "Kannur",
            "Kasaragod",
            "Kollam",
            "Kottayam",
            "Kozhikode",
            "Malappuram",
            "Palakkad",
            "Pathanamthitta",
            "Thiruvananthapuram",
            "Thrissur",
            "Wayanad"}, {"Kargil",
            "Leh"}, {"Agar Malwa",
            "Alirajpur",
            "Barwani",
            "Betul",
            "Bhopal",
            "Chhindwara",
            "Dewas",
            "Dhar",
            "Gwalior",
            "Hoshangabad",
            "Indore",
            "Jabalpur",
            "Khandwa",
            "Khargone",
            "Mandsaur",
            "Morena",
            "Raisen",
            "Ratlam",
            "Sagar",
            "Shajapur",
            "Sheopur",
            "Shivpuri",
            "Tikamgarh",
            "Ujjain",
            "Vidisha",
            "Other Region"}, {"Ahmadnagar",
            "Akola",
            "Amravati",
            "Aurangabad",
            "Bid",
            "Buldana",
            "Chandrapur",
            "Dhule",
            "Gondiya",
            "Hingoli",
            "Jalgaon",
            "Jalna",
            "Kolhapur",
            "Latur",
            "Mumbai",
            "Nagpur",
            "Nanded",
            "Nandurbar",
            "Nashik",
            "Osmanabad",
            "Palghar",
            "Parbhani",
            "Pune",
            "Raigarh",
            "Ratnagiri",
            "Sangli",
            "Satara",
            "Sindhudurg",
            "Solapur",
            "Thane",
            "Washim",
            "Yavatmal",
            "Other States",
            "Unknown"}, {"Imphal East",
            "Imphal West"}, {"East Khasi Hills",
            "Unknown"}, {"Aizawl"}, {"Baleshwar",
            "Bhadrak",
            "Cuttack",
            "Dhenkanal",
            "Jajapur",
            "Kalahandi",
            "Kendrapara",
            "Khordha",
            "Puri",
            "Sundargarh"}, {"Mahe",
            "Puducherry"}, {"Amritsar",
            "Barnala",
            "Faridkot",
            "Fatehgarh Sahib",
            "Firozpur",
            "Gurdaspur",
            "Hoshiarpur",
            "Jalandhar",
            "Kapurthala",
            "Ludhiana",
            "Mansa",
            "Moga",
            "Pathankot",
            "Patiala",
            "Rupnagar",
            "S.A.S. Nagar",
            "Sangrur",
            "Shahid Bhagat Singh Nagar",
            "Sri Muktsar Sahib"}, {"Ajmer",
            "Alwar",
            "Banswara",
            "Barmer",
            "Bharatpur",
            "Bhilwara",
            "Bikaner",
            "Churu",
            "Dausa",
            "Dhaulpur",
            "Dungarpur",
            "Hanumangarh",
            "Jaipur",
            "Jaisalmer",
            "Jhalawar",
            "Jhunjhunu",
            "Jodhpur",
            "Karauli",
            "Kota",
            "Nagaur",
            "Pali",
            "Pratapgarh",
            "Sawai Madhopur",
            "Sikar",
            "Tonk",
            "Udaipur",
            "Italians",
            "Evacuees"}, {"Ariyalur",
            "Chengalpattu",
            "Chennai",
            "Coimbatore",
            "Cuddalore",
            "Dharmapuri",
            "Dindigul",
            "Erode",
            "Kallakurichi",
            "Kancheepuram",
            "Kanniyakumari",
            "Karur",
            "Madurai",
            "Nagapattinam",
            "Namakkal",
            "Perambalur",
            "Pudukkottai",
            "Ramanathapuram",
            "Ranipet",
            "Salem",
            "Sivaganga",
            "Tenkasi",
            "Thanjavur",
            "The Nilgiris",
            "Theni",
            "Thiruvallur",
            "Thiruvarur",
            "Thoothukkudi",
            "Tiruchirappalli",
            "Tirunelveli",
            "Tirupathur",
            "Tiruppur",
            "Tiruvannamalai",
            "Vellore",
            "Viluppuram",
            "Virudhunagar"}, {"Adilabad",
            "Bhadradri Kothagudem",
            "Hyderabad",
            "Jagitial",
            "Jangoan",
            "Jayashankar",
            "Jogulamba Gadwal",
            "Kamareddy",
            "Karimnagar",
            "Khammam",
            "Kumuram Bheem Asifabad",
            "Mahabubabad",
            "Mahabubnagar",
            "Medak",
            "Medchal Malkajgiri",
            "Mulugu",
            "Nagarkurnool",
            "Nalgonda",
            "Nirmal",
            "Nizamabad",
            "Peddapalli",
            "Rajanna Sircilla",
            "Ranga Reddy",
            "Sangareddy",
            "Siddipet",
            "Suryapet",
            "Vikarabad",
            "Warangal Urban",
            "Unknown"}, {"Gomati",
            "North Tripura"}, {"Agra",
            "Aligarh",
            "Amroha",
            "Auraiya",
            "Azamgarh",
            "Baghpat",
            "Bahraich",
            "Balrampur",
            "Banda",
            "Bara Banki",
            "Bareilly",
            "Basti",
            "Bhadohi",
            "Bijnor",
            "Budaun",
            "Bulandshahr",
            "Etah",
            "Etawah",
            "Firozabad",
            "Gautam Buddha Nagar",
            "Ghaziabad",
            "Ghazipur",
            "Gonda",
            "Hapur",
            "Hardoi",
            "Hathras",
            "Jaunpur",
            "Kannauj",
            "Kanpur Nagar",
            "Kasganj",
            "Kaushambi",
            "Kheri",
            "Lucknow",
            "Mahrajganj",
            "Mainpuri",
            "Mathura",
            "Mau",
            "Meerut",
            "Mirzapur",
            "Moradabad",
            "Muzaffarnagar",
            "Pilibhit",
            "Pratapgarh",
            "Prayagraj",
            "Rae Bareli",
            "Rampur",
            "Saharanpur",
            "Sambhal",
            "Sant Kabir Nagar",
            "Shahjahanpur",
            "Shamli",
            "Shrawasti",
            "Sitapur",
            "Sultanpur",
            "Unnao",
            "Varanasi",
            "Ayodhya"}, {"Almora",
            "Dehradun",
            "Haridwar",
            "Nainital",
            "Pauri Garhwal",
            "Udham Singh Nagar"}, {"Darjeeling",
            "Hooghly",
            "Howrah",
            "Jalpaiguri",
            "Kalimpong",
            "Kolkata",
            "Medinipur East",
            "Murshidabad",
            "Nadia",
            "North 24 Parganas",
            "Paschim Bardhaman",
            "Purba Bardhaman",
            "South 24 Parganas",
            "Unknown"}};

    public static final String SOME_THING_WENT_WRONG = "Something Went Wrong" ;
    public static final String INTENT_STATE_NAME = "INTENT_STATE";
    public static final String INTENT_POSITION = "INTENT_POSITION";
}
